### PR TITLE
update to bevy 0.5

### PR DESCRIPTION
**Pull request by phrohdoh**
Still works as intended (*edit*: seems that isn't the case), here demoed with a smaller window (window size change is not part of this PR):
bevy-rider-on-bevy0 5

### CODE REVIEW

**Comment by bonsairobo** [comment]
I don't see anything obviously wrong in the PR but I tried running it and it's totally busted. There are a bunch of gaps between the lines and the sled just doesn't move at all.

**Comment by phrohdoh** [comment]
That's the exact behavior I experienced on current master, prior to making these changes, so thought that was the current state of the project.

**Comment by bonsairobo** [comment]
Hmm that's too bad. It worked a lot better back when I wrote it. Something must have changed upstream. I would like to fix it before merging the PR, but I won't have much time in the near term.

@phrohdoh Do you mind if I leave this open until I have time to investigate?

**Comment by phrohdoh** [comment]
> @phrohdoh Do you mind if I leave this open until I have time to investigate?

Do whatever you wish with the PR!
I fully license the code to you, however you want to use/license it.

I just love Line Rider and am thrilled at the idea of a Rust/Bevy implementation. :-)

**Comment by bonsairobo** [comment]
Actually, I guess it doesn't hurt to merge this and investigate with newer dependencies. I'll just make an issue instead.

**Comment by bonsairobo** [comment]
BTW @phrohdoh I fixed the bugs with the last couple commits on `master`

**Pull request merged**
